export function buildHomeRuntimeInputs(deps) {
  return {
    ...deps,
    chatPanel: deps.chatPanel,
    homePromptForm: deps.homePromptForm,
    homePromptInput: deps.homePromptInput,
    homeFileInput: deps.homeFileInput,
    homeUploadButton: deps.homeUploadButton,
    homeFilePreview: deps.homeFilePreview,
    homeModelSelect: deps.homeModelSelect,
    homeModelButton: deps.homeModelButton,
    homeModelMenu: deps.homeModelMenu,
    homeModelPicker: deps.homeModelPicker,
    projectGrid: deps.projectGrid,
    homeHistory: deps.homeHistory,
    syncHomeModelPicker: deps.syncHomeModelPicker,
    renderHomeHistory: deps.renderHomeHistory,
    renderAssets: deps.renderAssets,
    getActiveProject: deps.getActiveProject,
    updateProjectTitle: deps.updateProjectTitle,
    runCanvasTool: deps.runCanvasTool,
    setShapeTool: deps.setShapeTool,
    applyTextStyle: deps.applyTextStyle,
    toggleToolRailCollapsed: deps.toggleToolRailCollapsed,
    projectSaveStatus: deps.projectSaveStatus,
    uploadAsset: deps.uploadAsset,
    chatUploadImage: deps.chatUploadImage,
    chatImageInput: deps.chatImageInput,
    renderHomeFilePreview: deps.renderHomeFilePreview,
    setHomeFiles: deps.setHomeFiles,
    openHomeFilePicker: deps.openHomeFilePicker,
    setLibraryViewModeInMemory: deps.setLibraryViewModeInMemory,
    renderProjectLibrary: deps.renderProjectLibrary,
    selectLibraryProject: deps.selectLibraryProject,
    stepLibraryProject: deps.stepLibraryProject,
    openProject: deps.openProject,
    deleteProject: deps.deleteProject,
    setLibraryWheelLock: deps.setLibraryWheelLock,
    getLibraryWheelLock: deps.getLibraryWheelLock,
    setLibraryViewModeStorage: deps.setLibraryViewModeStorage,
    getPendingUploadPoint: deps.getPendingUploadPoint,
    newBlankProject: deps.newBlankProject,
    saveCurrentProject: deps.saveCurrentProject,
    generateHomeProject: deps.generateHomeProject,
    uploadAsReference: deps.uploadAsReference,
    addChatImageFiles: deps.addChatImageFiles,
    recordCanvasEvent: deps.recordCanvasEvent
  };
}

export function buildHomeRuntimeRefGroup({
  chatPanel,
  homePromptForm,
  homePromptInput,
  homeFileInput,
  homeUploadButton,
  homeFilePreview,
  homeModelSelect,
  homeModelButton,
  homeModelMenu,
  homeModelPicker,
  projectGrid,
  homeHistory,
  syncHomeModelPicker,
  renderHomeHistory,
  renderAssets,
  getActiveProject,
  updateProjectTitle,
  runCanvasTool,
  setShapeTool,
  applyTextStyle,
  toggleToolRailCollapsed,
  projectSaveStatus,
  uploadAsset,
  chatUploadImage,
  chatImageInput,
  renderHomeFilePreview,
  setHomeFiles,
  openHomeFilePicker,
  setLibraryViewModeInMemory,
  renderProjectLibrary,
  selectLibraryProject,
  stepLibraryProject,
  openProject,
  deleteProject,
  setLibraryWheelLock,
  getLibraryWheelLock,
  setLibraryViewModeStorage,
  getPendingUploadPoint,
  newBlankProject,
  saveCurrentProject,
  generateHomeProject,
  uploadAsReference,
  addChatImageFiles,
  recordCanvasEvent,
  libraryTransitionDirection,
  libraryViewMode
}) {
  return {
    chatPanel,
    homePromptForm,
    homePromptInput,
    homeFileInput,
    homeUploadButton,
    homeFilePreview,
    homeModelSelect,
    homeModelButton,
    homeModelMenu,
    homeModelPicker,
    projectGrid,
    homeHistory,
    syncHomeModelPicker,
    renderHomeHistory,
    renderAssets,
    getActiveProject,
    updateProjectTitle,
    runCanvasTool,
    setShapeTool,
    applyTextStyle,
    toggleToolRailCollapsed,
    projectSaveStatus,
    uploadAsset,
    chatUploadImage,
    chatImageInput,
    renderHomeFilePreview,
    setHomeFiles,
    openHomeFilePicker,
    setLibraryViewModeInMemory,
    renderProjectLibrary,
    selectLibraryProject,
    stepLibraryProject,
    openProject,
    deleteProject,
    setLibraryWheelLock,
    getLibraryWheelLock,
    setLibraryViewModeStorage,
    getPendingUploadPoint,
    newBlankProject,
    saveCurrentProject,
    generateHomeProject,
    uploadAsReference,
    addChatImageFiles,
    recordCanvasEvent,
    getLibraryTransitionDirection: () => libraryTransitionDirection,
    getLibraryViewMode: () => libraryViewMode
  };
}

export function buildHomeRuntimeSources(deps = {}) {
  const {
    chatPanel,
    homePromptForm,
    homePromptInput,
    homeFileInput,
    homeUploadButton,
    homeFilePreview,
    homeModelSelect,
    homeModelButton,
    homeModelMenu,
    homeModelPicker,
    projectGrid,
    homeHistory,
    syncHomeModelPicker,
    renderHomeHistory,
    renderAssets,
    getActiveProject,
    updateProjectTitle,
    runCanvasTool,
    setShapeTool,
    applyTextStyle,
    toggleToolRailCollapsed,
    projectSaveStatus,
    uploadAsset,
    chatUploadImage,
    chatImageInput,
    renderHomeFilePreview,
    setHomeFiles,
    openHomeFilePicker,
    setLibraryViewModeInMemory,
    renderProjectLibrary,
    selectLibraryProject,
    stepLibraryProject,
    openProject,
    deleteProject,
    setLibraryWheelLock,
    getLibraryWheelLock,
    setLibraryViewModeStorage,
    getPendingUploadPoint,
    newBlankProject,
    saveCurrentProject,
    generateHomeProject,
    uploadAsReference,
    addChatImageFiles,
    recordCanvasEvent,
    ...directHomeSources
  } = deps;

  const mappedHomeSources = {
    chatPanel,
    homePromptForm,
    homePromptInput,
    homeFileInput,
    homeUploadButton,
    homeFilePreview,
    homeModelSelect,
    homeModelButton,
    homeModelMenu,
    homeModelPicker,
    projectGrid,
    homeHistory,
    syncHomeModelPicker,
    renderHomeHistory,
    renderAssets,
    getActiveProject,
    updateProjectTitle,
    runCanvasTool,
    setShapeTool,
    applyTextStyle,
    toggleToolRailCollapsed,
    projectSaveStatus,
    uploadAsset,
    chatUploadImage,
    chatImageInput,
    renderHomeFilePreview,
    setHomeFiles,
    openHomeFilePicker,
    setLibraryViewModeInMemory,
    renderProjectLibrary,
    selectLibraryProject,
    stepLibraryProject,
    openProject,
    deleteProject,
    setLibraryWheelLock,
    getLibraryWheelLock,
    setLibraryViewModeStorage,
    getPendingUploadPoint,
    newBlankProject,
    saveCurrentProject,
    generateHomeProject,
    uploadAsReference,
    addChatImageFiles,
    recordCanvasEvent
  };
  return {
    ...directHomeSources,
    ...mappedHomeSources
  };
}

export function buildHomeRuntimeDependencyInputs({
  chatPanel,
  homePromptForm,
  homePromptInput,
  homeFileInput,
  homeUploadButton,
  homeFilePreview,
  homeModelSelect,
  homeModelButton,
  homeModelMenu,
  homeModelPicker,
  projectGrid,
  homeHistory,
  syncHomeModelPicker,
  renderHomeHistory,
  renderAssets,
  getActiveProject,
  updateProjectTitle,
  runCanvasTool,
  setShapeTool,
  applyTextStyle,
  toggleToolRailCollapsed,
  projectSaveStatus,
  uploadAsset,
  chatUploadImage,
  chatImageInput,
  renderHomeFilePreview,
  setHomeFiles,
  openHomeFilePicker,
  setLibraryViewModeInMemory,
  renderProjectLibrary,
  selectLibraryProject,
  stepLibraryProject,
  openProject,
  deleteProject,
  setLibraryWheelLock,
  getLibraryWheelLock,
  setLibraryViewModeStorage,
  getPendingUploadPoint,
  newBlankProject,
  saveCurrentProject,
  generateHomeProject,
  uploadAsReference,
  addChatImageFiles,
  recordCanvasEvent,
  ...directHomeInputs
}) {
  const mappedHomeInputs = {
    chatPanel,
    homePromptForm,
    homePromptInput,
    homeFileInput,
    homeUploadButton,
    homeFilePreview,
    homeModelSelect,
    homeModelButton,
    homeModelMenu,
    homeModelPicker,
    projectGrid,
    homeHistory,
    syncHomeModelPicker,
    renderHomeHistory,
    renderAssets,
    getActiveProject,
    updateProjectTitle,
    runCanvasTool,
    setShapeTool,
    applyTextStyle,
    toggleToolRailCollapsed,
    projectSaveStatus,
    uploadAsset,
    chatUploadImage,
    chatImageInput,
    renderHomeFilePreview,
    setHomeFiles,
    openHomeFilePicker,
    setLibraryViewModeInMemory,
    renderProjectLibrary,
    selectLibraryProject,
    stepLibraryProject,
    openProject,
    deleteProject,
    setLibraryWheelLock,
    getLibraryWheelLock,
    setLibraryViewModeStorage,
    getPendingUploadPoint,
    newBlankProject,
    saveCurrentProject,
    generateHomeProject,
    uploadAsReference,
    addChatImageFiles,
    recordCanvasEvent
  };
  return {
    ...directHomeInputs,
    ...mappedHomeInputs
  };
}

export function buildHomeRuntimeBootstrapBindings({
  chatPanel,
  homePromptForm,
  homePromptInput,
  homeFileInput,
  homeUploadButton,
  homeFilePreview,
  homeModelSelect,
  homeModelButton,
  homeModelMenu,
  homeModelPicker,
  projectGrid,
  homeHistory,
  syncHomeModelPicker,
  renderHomeHistory,
  renderAssets,
  getActiveProject,
  updateProjectTitle,
  runCanvasTool,
  setShapeTool,
  applyTextStyle,
  toggleToolRailCollapsed,
  projectSaveStatus,
  uploadAsset,
  chatUploadImage,
  chatImageInput,
  renderHomeFilePreview,
  setHomeFiles,
  openHomeFilePicker,
  setLibraryViewModeStorage,
  renderProjectLibrary,
  selectLibraryProject,
  stepLibraryProject,
  openProject,
  deleteProject,
  setLibraryViewModeInMemory,
  libraryWheelLock,
  setLibraryWheelLock,
  getLibraryTransitionDirection,
  getLibraryViewMode,
  getPendingUploadPoint,
  newBlankProject,
  saveCurrentProject,
  generateHomeProject,
  uploadAsReference,
  addChatImageFiles,
  recordCanvasEvent
} = {}) {
  const resolveLibraryViewMode = (mode) => {
    if (typeof setLibraryViewModeInMemory === "function") {
      setLibraryViewModeInMemory(mode);
    }
  };

  return {
    chatPanel,
    homePromptForm,
    homePromptInput,
    homeFileInput,
    homeUploadButton,
    homeFilePreview,
    homeModelSelect,
    homeModelButton,
    homeModelMenu,
    homeModelPicker,
    projectGrid,
    homeHistory,
    syncHomeModelPicker,
    renderHomeHistory,
    renderAssets,
    getActiveProject,
    updateProjectTitle,
    runCanvasTool,
    setShapeTool,
    applyTextStyle,
    toggleToolRailCollapsed,
    projectSaveStatus,
    uploadAsset,
    chatUploadImage,
    chatImageInput,
    renderHomeFilePreview,
    setHomeFiles,
    openHomeFilePicker,
    setLibraryViewModeInMemory: resolveLibraryViewMode,
    renderProjectLibrary,
    selectLibraryProject,
    stepLibraryProject,
    openProject,
    deleteProject,
    setLibraryWheelLock: (value) => {
      if (typeof setLibraryWheelLock !== "function") return;
      setLibraryWheelLock(value);
    },
    getLibraryWheelLock: () => libraryWheelLock,
    setLibraryViewModeStorage,
    getPendingUploadPoint,
    newBlankProject,
    saveCurrentProject,
    generateHomeProject,
    uploadAsReference,
    addChatImageFiles,
    recordCanvasEvent,
    getLibraryTransitionDirection,
    getLibraryViewMode
  };
}
