export function buildWorkspaceWorkflowRuntimeInputs(deps) {
  return {
    ...deps,
    bindTaskBarInteractions: deps.bindTaskBarInteractions,
    bindHomeLibraryInteractions: deps.bindHomeLibraryInteractions,
    bindCanvasMenuActions: deps.bindCanvasMenuActions,
    bindFooterEvents: deps.bindFooterEvents,
    bindCanvasRuntimeInfrastructure: deps.bindCanvasRuntimeInfrastructure,
    bindPromptSubmit: deps.bindPromptSubmit,
    bindPromptShortcuts: deps.bindPromptShortcuts,
    chatFloat: deps.chatFloat,
    collapseChat: deps.collapseChat,
    brandMenu: deps.brandMenu,
    projectMenu: deps.projectMenu,
    projectTitle: deps.projectTitle,
    jumpToCenterButton: deps.jumpToCenterButton,
    fitViewButton: deps.fitViewButton,
    commitProjectTitleEdit: deps.commitProjectTitleEdit,
    zoomRange: deps.zoomRange,
    zoomOutButton: deps.zoomOutButton,
    zoomInButton: deps.zoomInButton,
    returnToContentButton: deps.returnToContentButton,
    undoButton: deps.undoButton,
    redoButton: deps.redoButton,
    promptForm: deps.promptForm,
    chatModelSelect: deps.chatModelSelect,
    floatingLibrary: deps.floatingLibrary,
    closeLibraryButton: deps.closeLibraryButton,
    canvasViewport: deps.canvasViewport,
    homeWorkflow: deps.homeWorkflow
  };
}

export function buildWorkspaceWorkflowRuntimeRefGroup({
  bindTaskBarInteractions,
  bindHomeLibraryInteractions,
  bindCanvasMenuActions,
  bindFooterEvents,
  bindCanvasRuntimeInfrastructure,
  bindPromptSubmit,
  bindPromptShortcuts,
  chatFloat,
  collapseChat,
  brandMenu,
  projectMenu,
  projectTitle,
  jumpToCenterButton,
  fitViewButton,
  commitProjectTitleEdit,
  zoomRange,
  zoomOutButton,
  zoomInButton,
  returnToContentButton,
  undoButton,
  redoButton,
  promptForm,
  chatModelSelect,
  floatingLibrary,
  closeLibraryButton,
  canvasViewport,
  homeWorkflow
}) {
  return {
    bindTaskBarInteractions,
    bindHomeLibraryInteractions,
    bindCanvasMenuActions,
    bindFooterEvents,
    bindCanvasRuntimeInfrastructure,
    bindPromptSubmit,
    bindPromptShortcuts,
    chatFloat,
    collapseChat,
    brandMenu,
    projectMenu,
    projectTitle,
    jumpToCenterButton,
    fitViewButton,
    commitProjectTitleEdit,
    zoomRange,
    zoomOutButton,
    zoomInButton,
    returnToContentButton,
    undoButton,
    redoButton,
    promptForm,
    chatModelSelect,
    floatingLibrary,
    closeLibraryButton,
    canvasViewport,
    homeWorkflow
  };
}

export function buildWorkspaceWorkflowRuntimeSources(deps = {}) {
  const {
    bindTaskBarInteractions,
    bindHomeLibraryInteractions,
    bindCanvasMenuActions,
    bindFooterEvents,
    bindCanvasRuntimeInfrastructure,
    bindPromptSubmit,
    bindPromptShortcuts,
    chatFloat,
    collapseChat,
    brandMenu,
    projectMenu,
    projectTitle,
    jumpToCenterButton,
    fitViewButton,
    commitProjectTitleEdit,
    zoomRange,
    zoomOutButton,
    zoomInButton,
    returnToContentButton,
    undoButton,
    redoButton,
    promptForm,
    chatModelSelect,
    floatingLibrary,
    closeLibraryButton,
    canvasViewport,
    homeWorkflow,
    ...directWorkflowSources
  } = deps;

  const mappedWorkflowSources = {
    bindTaskBarInteractions,
    bindHomeLibraryInteractions,
    bindCanvasMenuActions,
    bindFooterEvents,
    bindCanvasRuntimeInfrastructure,
    bindPromptSubmit,
    bindPromptShortcuts,
    chatFloat,
    collapseChat,
    brandMenu,
    projectMenu,
    projectTitle,
    jumpToCenterButton,
    fitViewButton,
    commitProjectTitleEdit,
    zoomRange,
    zoomOutButton,
    zoomInButton,
    returnToContentButton,
    undoButton,
    redoButton,
    promptForm,
    chatModelSelect,
    floatingLibrary,
    closeLibraryButton,
    canvasViewport,
    homeWorkflow
  };
  return {
    ...directWorkflowSources,
    ...mappedWorkflowSources
  };
}

export function buildWorkspaceWorkflowRuntimeDependencyInputs({
  bindTaskBarInteractions,
  bindHomeLibraryInteractions,
  bindCanvasMenuActions,
  bindFooterEvents,
  bindCanvasRuntimeInfrastructure,
  bindPromptSubmit,
  bindPromptShortcuts,
  chatFloat,
  collapseChat,
  brandMenu,
  projectMenu,
  projectTitle,
  jumpToCenterButton,
  fitViewButton,
  commitProjectTitleEdit,
  zoomRange,
  zoomOutButton,
  zoomInButton,
  returnToContentButton,
  undoButton,
  redoButton,
  promptForm,
  chatModelSelect,
  floatingLibrary,
  closeLibraryButton,
  canvasViewport,
  homeWorkflow,
  ...directWorkflowInputs
}) {
  const mappedWorkflowInputs = {
    bindTaskBarInteractions,
    bindHomeLibraryInteractions,
    bindCanvasMenuActions,
    bindFooterEvents,
    bindCanvasRuntimeInfrastructure,
    bindPromptSubmit,
    bindPromptShortcuts,
    chatFloat,
    collapseChat,
    brandMenu,
    projectMenu,
    projectTitle,
    jumpToCenterButton,
    fitViewButton,
    commitProjectTitleEdit,
    zoomRange,
    zoomOutButton,
    zoomInButton,
    returnToContentButton,
    undoButton,
    redoButton,
    promptForm,
    chatModelSelect,
    floatingLibrary,
    closeLibraryButton,
    canvasViewport,
    homeWorkflow
  };
  return {
    ...directWorkflowInputs,
    ...mappedWorkflowInputs
  };
}

export function buildWorkspaceWorkflowRuntimeBootstrapBindings({
  bindTaskBarInteractions,
  bindHomeLibraryInteractions,
  bindCanvasMenuActions,
  bindFooterEvents,
  bindCanvasRuntimeInfrastructure,
  bindPromptSubmit,
  bindPromptShortcuts,
  chatFloat,
  collapseChat,
  brandMenu,
  projectMenu,
  projectTitle,
  jumpToCenterButton,
  fitViewButton,
  commitProjectTitleEdit,
  zoomRange,
  zoomOutButton,
  zoomInButton,
  returnToContentButton,
  undoButton,
  redoButton,
  promptForm,
  chatModelSelect,
  floatingLibrary,
  closeLibraryButton,
  canvasViewport,
  homeWorkflow
} = {}) {
  return {
    bindTaskBarInteractions,
    bindHomeLibraryInteractions,
    bindCanvasMenuActions,
    bindFooterEvents,
    bindCanvasRuntimeInfrastructure,
    bindPromptSubmit,
    bindPromptShortcuts,
    chatFloat,
    collapseChat,
    brandMenu,
    projectMenu,
    projectTitle,
    jumpToCenterButton,
    fitViewButton,
    commitProjectTitleEdit,
    zoomRange,
    zoomOutButton,
    zoomInButton,
    returnToContentButton,
    undoButton,
    redoButton,
    promptForm,
    chatModelSelect,
    floatingLibrary,
    closeLibraryButton,
    canvasViewport,
    homeWorkflow
  };
}
