import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, BadgeCheck, CreditCard, Database, FileText, LockKeyhole, MessageSquareWarning, Sparkles, UserRound } from "lucide-react";
import { Link, useLocation } from "react-router";
import "../features/commercial/commercial.css";
import { listPlans } from "../lib/api-client.js";

const pages = { "/pricing": { title: "Pricing", icon: Sparkles, eyebrow: "Plans" }, "/account": { title: "Account", icon: UserRound, eyebrow: "Account" }, "/account/billing": { title: "Billing", icon: CreditCard, eyebrow: "Billing" }, "/account/credits": { title: "Credits", icon: BadgeCheck, eyebrow: "Credits" }, "/account/security": { title: "Security", icon: LockKeyhole, eyebrow: "Security" }, "/account/data": { title: "Data", icon: Database, eyebrow: "Data" }, "/legal/terms": { title: "Terms of service", icon: FileText, eyebrow: "Legal" }, "/legal/privacy": { title: "Privacy policy", icon: LockKeyhole, eyebrow: "Legal" }, "/legal/refunds": { title: "Refund rules", icon: CreditCard, eyebrow: "Legal" }, "/legal/ai-disclosure": { title: "AI service notice", icon: Sparkles, eyebrow: "Legal" }, "/support/report": { title: "Report content", icon: MessageSquareWarning, eyebrow: "Support" }, "/support/appeal": { title: "Appeal", icon: MessageSquareWarning, eyebrow: "Support" } } as const;
const nav = [["/account", "Account"], ["/account/billing", "Billing"], ["/account/credits", "Credits"], ["/account/security", "Security"], ["/account/data", "Data"]] as const;

export default function CommercialRoute() {
  const location = useLocation(); const page = pages[location.pathname as keyof typeof pages] ?? pages["/account"]; const Icon = page.icon;
  return <main className="commercial-page"><header className="commercial-header"><Link className="commercial-back" to="/" aria-label="Back"><ArrowLeft size={18}/></Link><Link className="commercial-brand" to="/">AI Studio</Link><Link className="commercial-home-link" to="/">Home</Link></header><div className="commercial-shell"><aside className="commercial-nav"><Link className={location.pathname === "/pricing" ? "is-active" : ""} to="/pricing"><Sparkles size={18}/>Upgrade</Link>{nav.map(([href, label]) => <Link key={href} className={location.pathname === href ? "is-active" : ""} to={href}>{label}</Link>)}</aside><section className="commercial-content"><div className="commercial-heading"><span className="commercial-eyebrow">{page.eyebrow}</span><h1><Icon size={20}/>{page.title}</h1><p>Commercial controls follow provider readiness and do not create real charges before setup.</p></div>{location.pathname === "/pricing" ? <Pricing/> : <Panel path={location.pathname}/>}</section></div></main>;
}

function Pricing() { const plans = useQuery({ queryKey: ["catalog", "plans"], queryFn: listPlans }); return <div className="plan-grid">{plans.data?.map((plan) => <article className="plan-card" key={plan.priceId}><span className="plan-card__name">{plan.name}</span><strong>{new Intl.NumberFormat("en-US", { style: "currency", currency: plan.currency }).format(plan.amountFen / 100)}</strong><p>{plan.description}</p><ul><li><BadgeCheck size={16}/>{plan.credits} credits</li><li><BadgeCheck size={16}/>{plan.interval ?? "one-time"}</li></ul><button type="button" disabled>Available after payment setup</button></article>)}{plans.isLoading ? <p>Loading plans</p> : null}{!plans.isLoading && !plans.data?.length ? <p>No plans are available yet.</p> : null}</div>; }
function Panel({ path }: { path: string }) { const title = pages[path as keyof typeof pages]?.title ?? "Account"; return <div className="account-panel"><h2>{title}</h2><p>This area is ready for provider configuration without changing existing creation workflows.</p><div className="status-row"><span>Production actions</span><strong>Unavailable until configured</strong></div></div>; }
