export function createRuntimeChatContext(deps = {}) {
  const {
    recordCanvasEvent,
    addThinking,
    updateThinking,
    renderChatImagePreview,
    addChat,
    updateChat,
    addChatImage,
    addChatBlocks,
    addGenerationPreview,
    replacePreviewWithImage,
    replacePreviewWithModel,
    replacePreviewWithVideo,
    updateActiveProject,
    saveCurrentProject,
    saveCurrentProjectAfterGeneration,
    getActiveProject,
    makeProjectTitle,
    postJsonRequest,
    buildChatImagePayload,
    readFileAsDataUrl,
    readImageSourceAsDataUrl,
    detectGenerationKind,
    getPendingHomeGenerationFocus,
    setPendingHomeGenerationFocus,
    centerViewOnNode
  } = deps;

  return {
    recordCanvasEvent,
    addThinking,
    updateThinking,
    renderChatImagePreview,
    addChat,
    updateChat,
    addChatImage,
    addChatBlocks,
    addGenerationPreview,
    replacePreviewWithImage,
    replacePreviewWithModel,
    replacePreviewWithVideo,
    updateActiveProject,
    saveCurrentProject,
    saveCurrentProjectAfterGeneration,
    getActiveProject,
    makeProjectTitle,
    postJsonRequest,
    buildChatImagePayload,
    readFileAsDataUrl,
    readImageSourceAsDataUrl,
    detectGenerationKind,
    getPendingHomeGenerationFocus,
    setPendingHomeGenerationFocus,
    centerViewOnNode
  };
}
