export function buildChatRuntimeInputs(deps) {
  return {
    ...deps,
    recordCanvasEvent: deps.recordCanvasEvent,
    renderChatImagePreview: deps.renderChatImagePreview,
    addChat: deps.addChat,
    updateChat: deps.updateChat,
    addThinking: deps.addThinking,
    updateThinking: deps.updateThinking,
    addChatImage: deps.addChatImage,
    addChatBlocks: deps.addChatBlocks,
    addGenerationPreview: deps.addGenerationPreview,
    replacePreviewWithImage: deps.replacePreviewWithImage,
    replacePreviewWithVideo: deps.replacePreviewWithVideo,
    updateActiveProject: deps.updateActiveProject,
    saveCurrentProject: deps.saveCurrentProject,
    saveCurrentProjectAfterGeneration: deps.saveCurrentProjectAfterGeneration,
    getActiveProject: deps.getActiveProject,
    makeProjectTitle: deps.makeProjectTitle,
    postJsonRequest: deps.postJsonRequest,
    buildChatImagePayload: deps.buildChatImagePayload,
    readFileAsDataUrl: deps.readFileAsDataUrl,
    readImageSourceAsDataUrl: deps.readImageSourceAsDataUrl,
    detectGenerationKind: deps.detectGenerationKind,
    getPendingHomeGenerationFocus: deps.getPendingHomeGenerationFocus,
    setPendingHomeGenerationFocus: deps.setPendingHomeGenerationFocus,
    centerViewOnNode: deps.centerViewOnNode
  };
}

export function buildChatRuntimeRefGroup({
  recordCanvasEvent,
  renderChatImagePreview,
  addChat,
  updateChat,
  addThinking,
  updateThinking,
  addChatImage,
  addChatBlocks,
  addGenerationPreview,
  replacePreviewWithImage,
  replacePreviewWithVideo,
  updateActiveProject,
  saveCurrentProject,
  saveCurrentProjectAfterGeneration,
  getActiveProject,
  makeProjectTitle,
  postJsonRequest,
  buildChatImagePayload,
  readFileAsDataUrl,
  readImageSourceAsDataUrl,
  detectGenerationKind,
  getPendingHomeGenerationFocus,
  setPendingHomeGenerationFocus,
  centerViewOnNode
}) {
  return {
    recordCanvasEvent,
    renderChatImagePreview,
    addChat,
    updateChat,
    addThinking,
    updateThinking,
    addChatImage,
    addChatBlocks,
    addGenerationPreview,
    replacePreviewWithImage,
    replacePreviewWithVideo,
    updateActiveProject,
    saveCurrentProject,
    saveCurrentProjectAfterGeneration,
    getActiveProject,
    makeProjectTitle,
    postJsonRequest,
    buildChatImagePayload,
    readFileAsDataUrl,
    readImageSourceAsDataUrl,
    detectGenerationKind,
    getPendingHomeGenerationFocus,
    setPendingHomeGenerationFocus,
    centerViewOnNode
  };
}

export function buildChatRuntimeSources(deps = {}) {
  const {
    addThinking,
    updateThinking,
    recordCanvasEvent,
    renderChatImagePreview,
    addChat,
    updateChat,
    addChatImage,
    addChatBlocks,
    addGenerationPreview,
    replacePreviewWithImage,
    replacePreviewWithVideo,
    updateActiveProject,
    saveCurrentProject,
    saveCurrentProjectAfterGeneration,
    getActiveProject,
    makeProjectTitle,
    postJsonRequest,
    buildChatImagePayload,
    readFileAsDataUrl,
    readImageSourceAsDataUrl,
    detectGenerationKind,
    getPendingHomeGenerationFocus,
    setPendingHomeGenerationFocus,
    centerViewOnNode,
    ...directChatSources
  } = deps;

  const mappedChatSources = {
    recordCanvasEvent,
    renderChatImagePreview,
    addChat,
    updateChat,
    addThinking,
    updateThinking,
    addChatImage,
    addChatBlocks,
    addGenerationPreview,
    replacePreviewWithImage,
    replacePreviewWithVideo,
    updateActiveProject,
    saveCurrentProject,
    saveCurrentProjectAfterGeneration,
    getActiveProject,
    makeProjectTitle,
    postJsonRequest,
    buildChatImagePayload,
    readFileAsDataUrl,
    readImageSourceAsDataUrl,
    detectGenerationKind,
    getPendingHomeGenerationFocus,
    setPendingHomeGenerationFocus,
    centerViewOnNode
  };
  return {
    ...directChatSources,
    ...mappedChatSources
  };
}

export function buildChatRuntimeDependencyInputs({
  recordCanvasEvent,
  renderChatImagePreview,
  addChat,
  updateChat,
  addThinking,
  updateThinking,
  addChatImage,
  addChatBlocks,
  addGenerationPreview,
  replacePreviewWithImage,
  replacePreviewWithVideo,
  updateActiveProject,
  saveCurrentProject,
  saveCurrentProjectAfterGeneration,
  getActiveProject,
  makeProjectTitle,
  postJsonRequest,
  buildChatImagePayload,
  readFileAsDataUrl,
  readImageSourceAsDataUrl,
  detectGenerationKind,
  getPendingHomeGenerationFocus,
  setPendingHomeGenerationFocus,
  centerViewOnNode,
  ...directChatInputs
}) {
  const mappedChatInputs = {
    recordCanvasEvent,
    renderChatImagePreview,
    addChat,
    updateChat,
    addThinking,
    updateThinking,
    addChatImage,
    addChatBlocks,
    addGenerationPreview,
    replacePreviewWithImage,
    replacePreviewWithVideo,
    updateActiveProject,
    saveCurrentProject,
    saveCurrentProjectAfterGeneration,
    getActiveProject,
    makeProjectTitle,
    postJsonRequest,
    buildChatImagePayload,
    readFileAsDataUrl,
    readImageSourceAsDataUrl,
    detectGenerationKind,
    getPendingHomeGenerationFocus,
    setPendingHomeGenerationFocus,
    centerViewOnNode
  };
  return {
    ...directChatInputs,
    ...mappedChatInputs
  };
}

export function buildChatRuntimeBootstrapBindings({
  recordCanvasEvent,
  renderChatImagePreview,
  addChat,
  updateChat,
  addThinking,
  updateThinking,
  addChatImage,
  addChatBlocks,
  addGenerationPreview,
  replacePreviewWithImage,
  replacePreviewWithVideo,
  updateActiveProject,
  saveCurrentProject,
  saveCurrentProjectAfterGeneration,
  getActiveProject,
  makeProjectTitle,
  postJsonRequest,
  buildChatImagePayload,
  readFileAsDataUrl,
  readImageSourceAsDataUrl,
  detectGenerationKind,
  getPendingHomeGenerationFocus,
  setPendingHomeGenerationFocus,
  centerViewOnNode
} = {}) {
  return {
    recordCanvasEvent,
    renderChatImagePreview,
    addChat,
    updateChat,
    addThinking,
    updateThinking,
    addChatImage,
    addChatBlocks,
    addGenerationPreview,
    replacePreviewWithImage,
    replacePreviewWithVideo,
    updateActiveProject,
    saveCurrentProject,
    saveCurrentProjectAfterGeneration,
    getActiveProject,
    makeProjectTitle,
    postJsonRequest,
    buildChatImagePayload,
    readFileAsDataUrl,
    readImageSourceAsDataUrl,
    detectGenerationKind,
    getPendingHomeGenerationFocus,
    setPendingHomeGenerationFocus,
    centerViewOnNode
  };
}
