export function buildAgentRuntimeActionInputs(deps) {
  return {
    ...deps,
    directorActions: deps.directorActions,
    refreshDirectorOptions: deps.refreshDirectorOptions,
    runDirectorAction: deps.runDirectorAction,
    imageEditPopover: deps.imageEditPopover,
    addNodeMenu: deps.addNodeMenu,
    canvasContextMenu: deps.canvasContextMenu,
    assetUploadInput: deps.assetUploadInput,
    promptInput: deps.promptInput,
    getAddMenuPoint: deps.getAddMenuPoint,
    setAddMenuPoint: deps.setAddMenuPoint,
    getContextMenuPoint: deps.getContextMenuPoint,
    setContextMenuPoint: deps.setContextMenuPoint,
    setPendingUploadPoint: deps.setPendingUploadPoint,
    viewportPointToWorld: deps.viewportPointToWorld,
    hideAddNodeMenu: deps.hideAddNodeMenu,
    hideCanvasContextMenu: deps.hideCanvasContextMenu,
    showAddNodeMenu: deps.showAddNodeMenu,
    addNode: deps.addNode,
    addChat: deps.addChat,
    updateChat: deps.updateChat,
    renderChatImagePreview: deps.renderChatImagePreview,
    openAssetLibraryPanel: deps.openAssetLibraryPanel,
    appRoot: deps.appRoot,
    canvasWorld: deps.canvasWorld,
    presetSkill: deps.presetSkill,
    closeMenuWhenOutside: deps.closeMenuWhenOutside
  };
}

export function buildAgentRuntimeActionRefGroup({
  directorActions,
  refreshDirectorOptions,
  runDirectorAction,
  imageEditPopover,
  addNodeMenu,
  canvasContextMenu,
  assetUploadInput,
  promptInput,
  getAddMenuPoint,
  setAddMenuPoint,
  getContextMenuPoint,
  setContextMenuPoint,
  setPendingUploadPoint,
  viewportPointToWorld,
  panForZoomAroundWorldPoint,
  hideAddNodeMenu,
  hideCanvasContextMenu,
  showAddNodeMenu,
  showCanvasContextMenu,
  hideImageEditPopover,
  addNode,
  selectNode,
  addCanvasToolNode,
  createDrawingPreview,
  updateDrawingPreview,
  finishCanvasDrawing,
  startEraserDrag,
  updateEraserDrag,
  finishEraserDrag,
  createSelectionBox,
  updateSelectionBox,
  finishSelectionBox,
  getActiveCanvasTool,
  getLibraryAssets,
  addChat,
  openAssetLibraryPanel,
  appRoot,
  canvasWorld,
  presetSkill,
  closeMenuWhenOutside,
  isPointInAICore,
  updateAICoreDragState,
  uploadIntoAICore,
  uploadAsReference,
  hideAICoreWorkspace,
  runImageEditCommand,
  handleImageEditSubmit,
  handleImageEditCancel,
  toolRail,
  toggleToolRail,
  textFormatToolbar,
  textFontFamily,
  textFontWeight,
  textFontSize,
  textColorInput
}) {
  return {
    directorActions,
    refreshDirectorOptions,
    runDirectorAction,
    imageEditPopover,
    addNodeMenu,
    canvasContextMenu,
    assetUploadInput,
    promptInput,
    getAddMenuPoint,
    setAddMenuPoint,
    getContextMenuPoint,
    setContextMenuPoint,
    setPendingUploadPoint,
    viewportPointToWorld,
    panForZoomAroundWorldPoint,
    hideAddNodeMenu,
    hideCanvasContextMenu,
    showAddNodeMenu,
    showCanvasContextMenu,
    hideImageEditPopover,
    addNode,
    selectNode,
    addCanvasToolNode,
    createDrawingPreview,
    updateDrawingPreview,
    finishCanvasDrawing,
    startEraserDrag,
    updateEraserDrag,
    finishEraserDrag,
    createSelectionBox,
    updateSelectionBox,
    finishSelectionBox,
    getActiveCanvasTool,
    getLibraryAssets,
    addChat,
    openAssetLibraryPanel,
    appRoot,
    canvasWorld,
    presetSkill,
    closeMenuWhenOutside,
    isPointInAICore,
    updateAICoreDragState,
    uploadIntoAICore,
  uploadAsReference,
  hideAICoreWorkspace,
  runImageEditCommand,
  handleImageEditSubmit,
  handleImageEditCancel,
  toolRail,
  toggleToolRail,
  textFormatToolbar,
  textFontFamily,
  textFontWeight,
  textFontSize,
  textColorInput
  };
}

export function buildAgentRuntimeActionSources(deps = {}) {
  const {
    directorActions,
    refreshDirectorOptions,
    runDirectorAction,
    imageEditPopover,
    addNodeMenu,
    canvasContextMenu,
    assetUploadInput,
    promptInput,
    getAddMenuPoint,
    setAddMenuPoint,
    getContextMenuPoint,
    setContextMenuPoint,
    setPendingUploadPoint,
    viewportPointToWorld,
    hideAddNodeMenu,
    hideCanvasContextMenu,
    showAddNodeMenu,
    addNode,
    addChat,
    updateChat,
    renderChatImagePreview,
    openAssetLibraryPanel,
    appRoot,
    canvasWorld,
    presetSkill,
    closeMenuWhenOutside,
    imageEditSubmit,
    imageEditCancel,
    ...directActionSources
  } = deps;

  const mappedActionSources = {
    directorActions,
    refreshDirectorOptions,
    runDirectorAction,
    imageEditPopover,
    addNodeMenu,
    canvasContextMenu,
    assetUploadInput,
    promptInput,
    getAddMenuPoint,
    setAddMenuPoint,
    getContextMenuPoint,
    setContextMenuPoint,
    setPendingUploadPoint,
    viewportPointToWorld,
    hideAddNodeMenu,
    hideCanvasContextMenu,
    showAddNodeMenu,
    addNode,
    addChat,
    updateChat,
    renderChatImagePreview,
    openAssetLibraryPanel,
    appRoot,
    canvasWorld,
    presetSkill,
    closeMenuWhenOutside,
    imageEditSubmit,
    imageEditCancel
  };
  return {
    ...directActionSources,
    ...mappedActionSources
  };
}

export function buildAgentRuntimeDependencyActionInputs({
  directorActions,
  refreshDirectorOptions,
  runDirectorAction,
  imageEditPopover,
  addNodeMenu,
  canvasContextMenu,
  assetUploadInput,
  promptInput,
  getAddMenuPoint,
  setAddMenuPoint,
  getContextMenuPoint,
  setContextMenuPoint,
  setPendingUploadPoint,
  viewportPointToWorld,
  hideAddNodeMenu,
  hideCanvasContextMenu,
  showAddNodeMenu,
  addNode,
  addChat,
  updateChat,
  renderChatImagePreview,
  openAssetLibraryPanel,
  appRoot,
  canvasWorld,
  presetSkill,
  closeMenuWhenOutside,
  imageEditSubmit,
  imageEditCancel,
  handleImageEditSubmit,
  handleImageEditCancel,
  ...directActionInputs
}) {
  const mappedActionInputs = {
    directorActions,
    refreshDirectorOptions,
    runDirectorAction,
    imageEditPopover,
    addNodeMenu,
    canvasContextMenu,
    assetUploadInput,
    promptInput,
    getAddMenuPoint,
    setAddMenuPoint,
    getContextMenuPoint,
    setContextMenuPoint,
    setPendingUploadPoint,
    viewportPointToWorld,
    hideAddNodeMenu,
    hideCanvasContextMenu,
    showAddNodeMenu,
    addNode,
    addChat,
    updateChat,
    renderChatImagePreview,
    openAssetLibraryPanel,
    appRoot,
    canvasWorld,
    presetSkill,
    closeMenuWhenOutside,
    imageEditSubmit: imageEditSubmit ?? handleImageEditSubmit,
    imageEditCancel: imageEditCancel ?? handleImageEditCancel
  };
  return {
    ...directActionInputs,
    ...mappedActionInputs
  };
}

export function buildAgentRuntimeBootstrapActionBindings({
  directorActions,
  refreshDirectorOptions,
  runDirectorAction,
  imageEditPopover,
  addNodeMenu,
  canvasContextMenu,
  assetUploadInput,
  promptInput,
  getAddMenuPoint,
  setAddMenuPoint,
  getContextMenuPoint,
  setContextMenuPoint,
  setPendingUploadPoint,
  viewportPointToWorld,
  panForZoomAroundWorldPoint,
  hideAddNodeMenu,
  hideCanvasContextMenu,
  showAddNodeMenu,
  showCanvasContextMenu,
  hideImageEditPopover,
  addNode,
  selectNode,
  addCanvasToolNode,
  createDrawingPreview,
  updateDrawingPreview,
  finishCanvasDrawing,
  startEraserDrag,
  updateEraserDrag,
  finishEraserDrag,
  createSelectionBox,
  updateSelectionBox,
  finishSelectionBox,
  getActiveCanvasTool,
  getLibraryAssets,
  addChat,
  openAssetLibraryPanel,
  appRoot,
  canvasWorld,
  presetSkill,
  closeMenuWhenOutside,
  isPointInAICore,
  updateAICoreDragState,
  uploadIntoAICore,
  uploadAsReference,
  hideAICoreWorkspace,
  runImageEditCommand,
  handleImageEditSubmit,
  handleImageEditCancel,
  toolRail,
  toggleToolRail,
  textFormatToolbar,
  textFontFamily,
  textFontWeight,
  textFontSize,
  textColorInput
} = {}) {
  return {
    directorActions,
    refreshDirectorOptions,
    runDirectorAction,
    imageEditPopover,
    addNodeMenu,
    canvasContextMenu,
    assetUploadInput,
    promptInput,
    getAddMenuPoint,
    setAddMenuPoint,
    getContextMenuPoint,
    setContextMenuPoint,
    setPendingUploadPoint,
    viewportPointToWorld,
    panForZoomAroundWorldPoint,
    hideAddNodeMenu,
    hideCanvasContextMenu,
    showAddNodeMenu,
    showCanvasContextMenu,
    hideImageEditPopover,
    addNode,
    selectNode,
    addCanvasToolNode,
    createDrawingPreview,
    updateDrawingPreview,
    finishCanvasDrawing,
    startEraserDrag,
    updateEraserDrag,
    finishEraserDrag,
    createSelectionBox,
    updateSelectionBox,
    finishSelectionBox,
    getActiveCanvasTool,
    getLibraryAssets,
    addChat,
    openAssetLibraryPanel,
    appRoot,
    canvasWorld,
    presetSkill,
    closeMenuWhenOutside,
    isPointInAICore,
    updateAICoreDragState,
    uploadIntoAICore,
  uploadAsReference,
  hideAICoreWorkspace,
  runImageEditCommand,
  handleImageEditSubmit,
  handleImageEditCancel,
  toolRail,
  toggleToolRail,
  textFormatToolbar,
  textFontFamily,
  textFontWeight,
  textFontSize,
  textColorInput
  };
}
